### ISSUE TITLE
nest stores into groups?

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-frontend#103]
How i imagine the hierarchy: `Page -> Group -> Store`
**shouldn't the url represent this (i.e. `/#!/Berlin/store/15`) and the components as well?**

![hierachy](https://cloud.githubusercontent.com/assets/10246027/19689888/251ec7d4-9acf-11e6-970b-2f58dbd64239.png)

in #84 there is currently a discussion about how to shape the data flow.
The reactway would be having the active groupId in _home_ and passing it down all the way to _groupMenu_ & _groupDetails_

right now the hierachy seems really chaotic and randomly, so we should create more mockups! :)

**Comment by tiltec** [comment]
Looks good @alangecker!
I don't agree that what we have now is totally random and chaotic, but there surely can be many improvements!

To your points:
We have now `groupDetail`, which is essentially the homepage (it contains the topbar and the group details).

URL scheme could be `/<groupname>/store/<storename>` - it's currently not possible, as the groupname is not unique & urlsafe, and the storename is not unique per group, but I could implement this in the backend.

General URL scheme:

- `/<groupname>/` - group overview page (home)
- `/<groupname>/members` - detailed list of members
- `/<groupname>/stores/` - list of all stores in the group
- `/<groupname>/stores/<storename>` - store details
- `/login` and `/signup` for the usual stuff

**Comment by D0nPiano** [comment]
Makes sense to me! I'm for the new URLs and making the groupName unique. ...is foodsharing.de allowing the same store name for two stores currently, @tiltec? e.g. when there are multiple REWE in one place?

I like the mochup and would be for implementing it this way in the desktop version - it'd only need to look good on mobile devices to (which might get a little messy)

> The reactway would be having the active groupId in home and passing it down all the way to groupMenu & groupDetails

I agree, I'd also really prefer it that way. Just having home have topbar & footer, and a view in the middle.

**Comment by tiltec** [comment]
@D0nPiano
> is foodsharing.de allowing the same store name for two stores currently, @tiltec? e.g. when there are multiple REWE in one place?

Yes, it is allowed. But it's not so nice in lists when there are 5 stores with the same name.

The rationale for having unique store names per group could be something like this: users will use the name to refer to a store and not the ID, so make it easier for them to keep distinct names.
Rationale for not having globally unique store names: the groups have no interaction and users are mostly active in one group.

**Comment by tiltec** [comment]
Update: I thought about it a bit and unique names in URLs are not good. To make them safe and nice (no %20s in the URL), we would need to forbid spaces and umlauts.

New proposal: use IDs

- `/group/<groupid>/` - group overview page (home)
- `/group/<groupid>/members` - detailed list of members
- `/group/<groupid>/stores/` - list of all stores in the group
- `/group/<groupid>/stores/<storeid>` - store details
- `/login` and `/signup` for the usual stuff

**Comment by D0nPiano** [comment]
Actually, is there a specific reason to have a whole page just for members? I'd prefer to just have it in groupDetail for now I think. Other than that it sounds good to me.

**Comment by tiltec** [comment]
We can leave the tabbed interface for now, but having pages could be convenient to have deeper URLs.
Can the URLs also point at one tab? Then we can combine both approaches :)

I would even prefer having URLs for stuff like "create store", "edit store", "create pickup date", "edit pickup date". Don't how easy this can be done with uirouter

**Comment by nicksellen** [comment]
I think have meaningful content in the url is nice (and incremental ids are not nice, as you can guess the next one), and the usual way is to have a unique _slug_ field in the db, which then needs special handling to make sure urls aren't broken on rename, etc... which means quite a lot of work which is easy to get wrong.

I would argue to keep with numeric ids for now for simplicity. You can get quite a long way with this approach...

Having the urls as @tiltec suggested seems good to me, would mean make it more effecient for loading the related group in the resolve function (https://github.com/yunity/foodsaving-frontend/blob/master/client/app/components/storeDetail/storeDetail.js#L36) as they can load in parallel (would need to check the group is is actually correct for the store too...
