### ISSUE TITLE
Remove usages of first & last name

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#105]
display_name is more than enough right now, let's not depend on first & last name (they are optional in the backend)

I would add them later if needed (e.g. for legal reasons).

**Comment by Sliverriver** [comment]
was there discussion anything if people should use their real names on the plattform? i really appreciate it not seeing any fake or nicknames on foodsharing - and not having it like second facebook with weird and crypted names. 

just point me where i can rant about this :-D

**Comment by tiltec** [comment]
I'd assume that `display_name` is enough for giving the tool to test users, so I'd give this task green light.
It's only used in signup and usersList components.
