### ISSUE TITLE
What logo should we use for the foodsaving tool?

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#110]
I think it should be different from the yunity logo, as this is not _the yunity software_.

It will be used in the headline, something smaller should be used as favicon.

One idea from Luisa in Copenhagen (that some found quite aggressive :) ) 
![fist-the-carrot](https://cloud.githubusercontent.com/assets/4410802/19742444/62eb3efc-9bc5-11e6-8588-d8c241f2fdfb.png)

We can also switch the logo later to something _more mature_ when we are in production. Maybe just use a picture of a seed for now

**Comment by Sliverriver** [comment]
To aggressive - looks for some like a knife - resembles violence.

**Comment by PaulFree14** [comment]
how about implementing the ∞ somehow in the logo?

**Comment by PaulFree14** [comment]
first question when it comes to talk about which logo: 
What is the message we want to communicate?
Which emotion do we want to effect?

**Comment by D0nPiano** [comment]
There was a carrot on a lifebelt somewhere (couldn't find it in slack / wiki). Is that still a proposal and does anyone know what I'm talking about and where the image is at?

**Comment by tiltec** [comment]
![save-carrot](https://cloud.githubusercontent.com/assets/4410802/19970009/eb0a70d0-a1da-11e6-84dd-31cd1134393b.png)

[save-carrot.zip](https://github.com/yunity/foodsaving-frontend/files/569240/save-carrot.zip)

**Comment by tiltec** [comment]
> What is the message we want to communicate?

There's food out there that is going to be thrown away every day, get active and save it!

> Which emotion do we want to effect?

Urgency, appetite, positivism, sense of community, sense of doing something good

**Comment by alangecker** [comment]
proposal from my lovely sister:
![15356795_1351246818253293_1698537270_n](https://cloud.githubusercontent.com/assets/10246027/20951475/36740df0-bc26-11e6-8710-ca5e23aac2b3.jpg)

**Comment by tiltec** [comment]
Looks good, sister of @alangecker !
Do you maybe have a SVG of that?

**Comment by alangecker** [comment]
https://gist.github.com/alangecker/2d8ffda9318408cb1ff02e555a1e8862

**Comment by djahnie** [comment]
Like the one of Chandis sister!
Looks friendly and playful, let's use it!

**Comment by alangecker** [comment]
she's working on version which is better visible as a small icon and on a monochrome version as well, updates soon... ;)

**Comment by djahnie** [comment]
Does she maybe also have a name? I even mentioned her in the [heartbeat](https://yunity.atlassian.net/wiki/display/YUN/yunity+heartbeat+2016-12-11) just calling her _the sister of Chandi_...^^

**Comment by alangecker** [comment]
sandra ;)

**Comment by tiltec** [comment]
Ok, let's use Sandra's logo :)

**Comment by tiltec** [comment]
#222
