### ISSUE TITLE
Editable fields

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#123]
Enable the user to change group/store/pickupdate fields (e.g. name, description).

**Comment by D0nPiano** [comment]
Shall we use xeditable (like in mvp-design.yunity.org) again? https://vitalets.github.io/angular-xeditable/
- MIT license
- doesn't seem outdated
- huge set of options
- seems well documented

**Comment by tiltec** [comment]
Seems perfect!
