### ISSUE TITLE
Join group component

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#124]
List all groups and click to join them. Probably in combination with groupMenu.

Could also be integrated in the signup page, show the user the most actives group to directly join?

**Comment by Xbaal** [comment]
If you are in no group, the home component shows such a thing currently.
But i would like to have a seperate component for this to be honest. And a more nice-looking one.

**Comment by tiltec** [comment]
Maybe a partial component that is shown via mdDialog in `home` if the user is in no group?
