### ISSUE TITLE
Map integration

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#130]
When we eventually want to include a map, does anyone know a good angular friendly way? The mvp-design was using https://github.com/tombatossals/angular-leaflet-directive, but it wasn't really updated for a year. I didn't find anything else / better either though.

**Comment by tiltec** [comment]
The leaflet-directive seems good, it's mentioned here: https://github.com/gianarb/awesome-angularjs

Potential mapping goals:

1. per group: all stores for overview. click on the store, go to the store page
2. on the store page: _where is the store exactly?_
2. public: locations of all groups. could be the start page for unregistered users. click on a group joins group

What do you think?

**Comment by tiltec** [comment]
angular-ui has a fork of the leaflet directive: https://github.com/angular-ui/ui-leaflet
It's under active development, I would give it a try.
