### ISSUE TITLE
Enhance user profile

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#155]
I identified to following enhancements for foodsavers from DLC Nantes and possibly other:

- users can add their facebook profile link
- users can add their phone number

**Comment by tiltec** [comment]
Is a simple textarea fitting the purpose? Would implement this in the backend.

**Comment by djahnie** [comment]
To add a simple text field sounds reasonable.
People can add whatever information they see fit. So people who don't have facebook aren't forced to enter data which is not available and info on other stuff like transportation capabilities could also be inserted.
