### ISSUE TITLE
Should pickups have a duration?

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#156]
Identified requirement: show users how long a pickup will take.

Possible solutions:

- as extra text field to the pickup
- as `end` time field

**Comment by alangecker** [comment]
guess it isn't necessary to have a machine readable end time and a text field is more flexible, useful for vague times like "max. 1h" or "circa 10 min"

**Comment by tiltec** [comment]
Yep, it's easiest to add an optional `comment` field to the pickup date.

**Comment by tiltec** [comment]
Comment field will be tracked in #158
