### ISSUE TITLE
Users should note down their means of transport (car, bike trailer)

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#157]
Helpful for co-collectors to see how much transportation capacity is at a pickup.

Possible solutions:

- per-user text field: write it down once, can't change it per pickup
- per-pickup text field: different transport for each pickup possible. could be possible to remember the last value for convenience.

**Comment by djahnie** [comment]
A free text field on the user page offers unlimited possibilities to add info... So I'm definitely in favor of that!
A free text field per pick-up on the store page adds the flexibility to request a car or whatever if needed, like it as well!

**Comment by tiltec** [comment]
Solved it with #207
