### ISSUE TITLE
Adjust title accoding to page

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#161]
The content of the page could be reflected in the title. Currently, it just shows "Foodsaving".
It could show:

- Name of the active group
- Name of the store (when on store page)
- ...

**Comment by D0nPiano** [comment]
Shall I just add
`$window.document.title = Group.name + " | Foodsaving"; `
to all controllers? I couldn't really find a nicer version, especially with resolved data.

**Comment by tiltec** [comment]
This would be something where a common parent `group` view would be helpful ( #167 ). Maybe a good cause for it?

**Comment by D0nPiano** [comment]
Yeah, sounds like a good idea. Also pretty helpful for adding breadcrums (#173) later.

**Comment by D0nPiano** [comment]
So, both for title & breadcrumbs I'd suggest using some other module. I found https://github.com/ncuillery/angular-breadcrumb, it's MIT licensed and seems reasonable. We could use the breadcrumbs and also the `getStatesChain` function, that returns an array of the names, to adjust our title (e.g. 'Pickups | Groupname | Foodsaving')

**Comment by tiltec** [comment]
Sounds perfect! The only requirement seems that we actually need to nest the ui-router states (currently just the URLs are nested). But that seems to be a sane design anyways ;)

**Comment by D0nPiano** [comment]
Actually I just changed the whole groupMultiView thingy to nested states. So it's actually really perfect :)
