### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#173]
Adding breadcrumbs would make it easier to go back to the last page visited

**Comment by alangecker** [comment]
since the new store multiview #237  is a hierarchy structure, each by the breadcrumbs represented part is still visible on the page.
Doesn't that make the breadcrumbs redundant?

**Comment by D0nPiano** [comment]
Actually, agreed. I also thought of just removing them completely. It's good to include ncy-breadcrumb for our page titel, but displaying the breadcrumbs seems a little pointless.
