### ISSUE TITLE
use $mdToast to show 400/500 errors

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-frontend#185]

**Comment by tiltec** [comment]
Which location in the code would be best for this?

I imagine that it would be best in the component itself, where the request originates. So we only need to display the errors that are critical/not handled otherwise.

**Comment by tiltec** [comment]
I thought that it might be solvable with an Angular decorator, but it doesn't work and is not a good idea anyways.

So back to plan A: individually at each request. I tend to create a service for that...

**Comment by D0nPiano** [comment]
### 400 & 500

So in the end, we are just adding a catch block to all requests?
```
class GroupService {
   ...
  get(groupId) {
    return this.$http.get('/api/groups/${groupId}/')
      .then((res) => res.data)
      .catch((data) => {
        // Display Toast
        $errorHandler.showToast("Couldn't load groupdata")
    });
  }
```
Alternatively, I found [this tutorial](http://www.codelord.net/2014/06/25/generic-error-handling-in-angularjs/ ) that also uses decorators. What was your reason not to use a general approach, @tiltec?

### 404
Something like
```
$rootScope.$on('$stateChangeError', (event) => {
  $state.go('404');
});
```
for 404s after #272 is done?

**Comment by tiltec** [comment]
> What was your reason not to use a general approach, @tiltec?

Don't remember exactly, but I think the problem was that I couldn't load $mdToast in the decorator. But now I have more angular knowledge and _might_ be able to do it ;)

The approach outlined in the tutorial seems to be fine, maybe with less verbose names though.
Do you want to work on it? I could give it another try after finalizing the recurring pickups.

About 404: not so sure we need one - just redirecting to the group seems to be fine for me :D

**Comment by D0nPiano** [comment]
> Do you want to work on it? I could give it another try after finalizing the recurring pickups.

Well, at the moment I'd rather work on making it the website a little more mobile-friendly (have a small list in my mind of things I want to try), so if you are motivated to work on this, go ahead! 🙂

**Comment by tiltec** [comment]
#312 adds a toast for timeout and internal server error. I think the other errors should be handled inside the controller, because HTTP4xx usually mean wrong data.

Of course we could log statistics to make us aware of errors.
