### ISSUE TITLE
No automatic line breaks in group and store descriptions

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#197]
When writing a lot of text in the description fields of groups or stores no automatic line breaks are effected.
The text thus exceeds the box and goes on to the right as long as needed.
It can be read using the scroll bar, that appears on the lower end of the screen (I tried using chrome), but it looks pretty shitty.

**Comment by alangecker** [comment]
the way how the description gets displayed gets rewritten in #203, which should solve the problem ;)
