### ISSUE TITLE
Have a hackathon?

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#209]
I'll be in Valencia (Spain) in January/February, would organize something if I get help.

**Comment by PaulFree14** [comment]
What kind of support you need. 
I could imagine helping with sending some invitations out. I guess I won't make it to spain soon. 
Can you manage to get a place or would you like support there. (I've read nick is looking for the trustroot location. any more support needed with space?)

**Comment by tiltec** [comment]
So.. given that I expect some yuniteers to be in Valencia end of January, I would

1. find a place where we can sleep, cook, work
2. find a common time where we have the open hackathon (e.g. 3 days or 1 week)
3. make it definite and public

Note that even if (1) does not work out perfectly, we might still be able to have a hackathon at some nice coworking space, while sleeping at couchsurfing places.

**Comment by djahnie** [comment]
Is this still a plan, even though we may relocate our focus on Barcelona now?
So far I didn't contact any coworking spaces or anything, because I wasn't sure, if we still wanna do a Valencia hackathon...

Also: Is it smart to duplicate this info or split it up rather between here and Slack? Where is the benefit?

**Comment by NerdyProjects** [comment]
Having this info here means I get an email :D I would come to your hackathon :)))

**Comment by tiltec** [comment]
Might be good to have on GitHub: it's public & linkable and it adds to coder street credibility ;)

I would try to pursue events in both places, but first in Barcelona and later in Valencia.

Maybe end of January in Barca and mid of Feb in Valencia?

**Comment by alangecker** [comment]
wasn't really a hackathon, but i guess we can close that now ;)

**Comment by tiltec** [comment]
Hey hey, not so quick ;) We've just arrived in Valencia... you come here as well?
