### ISSUE TITLE
Write a short help about markdown for group/user/store description fields

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#210]
Could be shown when editing the page.

**Comment by djahnie** [comment]
Should it be shown somewhere all the time (like the mini formatting help in Slack) or should it be somehow clickable or expandable and thus more elaborate?

**Comment by tiltec** [comment]
I like a small mini help like in slack that could be shown on the side. Additionally, we could link to a complete markdown tutorial like https://guides.github.com/features/mastering-markdown/
