### ISSUE TITLE
Use local date format for pickup dates

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#217]
Currently it uses the German format: 20.01.2016
That's not very localized.

Three options:

- Should detect the local format of the user (via the browser)
- should use the same as the angular-translate locale
- just use ISO8601 (2016-01-20) for simplicity

**Comment by D0nPiano** [comment]
I'm against using ISO8601. My favorite would be defining it in our angular translate files [I think your number 2]

**Comment by tiltec** [comment]
That may be possible, but I don't know how...

**Comment by alangecker** [comment]
resolved with #300
