### ISSUE TITLE
Persist currentGroup

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#218]
## Problem

when opening a user page directly, the group is not set.

## Solution

Let's store the currentGroup on the server.

Retrieve it when the page opens. Save it when you open another group. Could be embedded in the currentGroupService.

## Other solution

Simpler would be to just use localstorage/cookie.

**Comment by tiltec** [comment]
Associated backend task: https://github.com/yunity/foodsaving-backend/issues/277

**Comment by ShababShahriar** [comment]
Is this still open for contribution? Would like to work on it if no one else is.

**Comment by tiltec** [comment]
Backend is already done https://github.com/yunity/foodsaving-backend/pull/286 , needs frontend implementation.

**Comment by ShababShahriar** [comment]
Up for it.

**Comment by tiltec** [comment]
Is this information sufficient for you?

> Retrieve it when the page opens. Save it when you open another group. Could be embedded in the currentGroupService.

When using the currentGroup service, I assume it will only be a few lines of additional code there.

**Comment by tiltec** [comment]
Code locations:

Setting the current group: https://github.com/yunity/foodsaving-frontend/blob/master/client/app/components/group/group.js#L60

Switching to the first group after login: https://github.com/yunity/foodsaving-frontend/blob/master/client/app/components/home/home.controller.js#L15

Call the backend to modify user details: https://github.com/yunity/foodsaving-frontend/blob/master/client/app/services/user/user.service.js#L29
(is using PATCH, so you only need to send the changed data: the user id and the current_group id)

Service to save the current group in the browser
https://github.com/yunity/foodsaving-frontend/blob/master/client/app/services/group/currentGroup.service.js
could be used to call the User.save function when the set() function is called (needs to get the user id from the Authentication.update method)

Auth update
https://github.com/yunity/foodsaving-frontend/blob/master/client/app/services/authentication/authentication.service.js#L17
returns the user details if the user is logged in

**Comment by tiltec** [comment]
It works, we should refactor the code locations in future though.
