### ISSUE TITLE
Cosmetic bug: leaflet buttons over popup

### ISSUE THREAD

**Issue by Xbaal** [yunity/foodsaving-frontend#226]
Leaflet buttons and the stuff in the bottom right have higher z-index than the createPickup popup.

**Comment by tiltec** [comment]
StoreDetail page?

**Comment by Xbaal** [comment]
https://fstool.yunity.org/#!/group/13/store/14
Firefox
<a href="http://www.directupload.net" target="_blank"><img src="http://fs5.directupload.net/images/161214/ykhqbntt.png" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by tiltec** [comment]
Ok, I see. It seems to be no problem on the groupDetail view, I wonder what's going on...
The createStore on groupDetail dialog loads its own map, maybe that's the reason?
