### ISSUE TITLE
Add confirmation Dialog to leave Group

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#231]

**Comment by tiltec** [comment]
Good idea, I think it makes sense, but it's not a high priority to me..

**Comment by tiltec** [comment]
After getting feedback from Nantes, I would add the delete pickup confirmation soon.

**Comment by tiltec** [comment]
Confirmation for delete pickup is implemented.

**Comment by alangecker** [comment]
resolved with #273
