### ISSUE TITLE
Should we put "isSmallScreen" in root scope?

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#233]
Currently in groupDetailMultiView #174 and SideNav #232, the Components use ng-if to change it's layout depending on screen size. The value for ng-if is determined by a the $mdMedia service of angular material, and the var "isSmallScreen" is declared in every scope that uses it.

So, to avoid rewriting the same statement (and having multiple watch statements for basically the same variable) I'd suggest moving it to app.ctrl and defining "isSmallScreen" in root scope.

What do you think? @nicksellen @tiltec? Or anyone who has a clue about using the root Scope in angular?

**Comment by tiltec** [comment]
It seems that the alternative would be a service: https://stackoverflow.com/questions/16739084/angularjs-using-rootscope-as-a-data-store

From a testing perspective, having things depending on $rootScope seems like a bad idea (components are tested in isolation, only loading dependencies). Should app.ctrl be a dependency of every component?.
Whereas we could just inject the service when we need it.

So... I'm for using a service, maybe call it "screenSizeService"? But it also sounds a bit complicated... 

Can we somehow store it as configuration? (app.config)

**Comment by D0nPiano** [comment]
Well, agreed. I think I'd just use the $mdMedia service then. It's documented and we wouldn't have to write our own service that just stores one value. And I also found a way prettier way to implement it (no clue why I was putting it in that ugly in the scope before....). So I'm for writing:
` ng-if="$ctrl.$mdMedia('gt-sm')"`

**Comment by tiltec** [comment]
> ng-if="$ctrl.$mdMedia('gt-sm')"

sounds good! Last time I also tried that, but somehow it didn't work... maybe I did something else wrong.
