### ISSUE TITLE
Check why some users don't see their preferred language

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#238]
I got feedback from Clement that some users see the English page, while they expect to see a French version.

**Comment by tiltec** [comment]
When I set my browser to French, it gives me the French version. vice versa when I set it to English.
Can this be automatically tested?

Is there another method to determine the language? currently it relies on the `Accept-Language` header

**Comment by djahnie** [comment]
Which browsers did you test it with apart from firefox?
Want me to try with chrome and ie?

**Comment by tiltec** [comment]
Oh right, that's missing information. I tested it in Chrome. (But all browser send the `Accept-Language` header, although some people might have wrong browser configuration)

If you test it, be sure to clear the cookies before (or use a new browser session), as the website remembers the last chosen language via cookie storage.

Other methods I could think of:

- IP-based location guess and derive the language from it (I think that's worse than the current solution)
- Make the language part of the URL, use this to override the guess (e.g. add `/?lang=de` at the end). Helps when people in one language region copy-paste links to each other

**Comment by djahnie** [comment]
Tried in ie11 and it gave me German, even though it should have been French...

I also think that the IP-based location guess is worse than what's currently happening. The language sensitive URL sounds not so bad, though...

**Comment by tiltec** [comment]
I found this [nice tool](https://validator.w3.org/i18n-checker/check?uri=https%3A%2F%2Ffstool.yunity.org#validate-by-uri+)

It also shows the `Accept-Language` header of the client (your browser). Mine is `Accept-Language: en-US,en;q=0.5`, therefore I expect English.
What does it show for you?

**Comment by djahnie** [comment]
Yep, it shows exactly what I entered: `Accept-Language: fr-FR,de-DE;q=0.7,en-US;q=0.3`, therefore I'd expect French, afterwards German and lastly English.

**Comment by tiltec** [comment]
That's right… the special case there is the missing `q` value for `fr-FR`. It should default to 1, but maybe angular-translate fails to understand this.

**Comment by tiltec** [comment]
angular-translate uses the following browser properties to determine the language:

- navigator.languages[0]
- navigator.language

`navigator.languages[0]` should be similar to `Accept-Language`: https://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

I think if a user/browser/extension just sets the `Accept-Language` header, then `navigator.languages[0]` would not reflect this.
@djahnie how did you change the header?

**Comment by tiltec** [comment]
I will assume that this works until I get more feedback that it doesn't. At some point it could make sense to put some analytics in place to detect errors like this by ourselves.
