### ISSUE TITLE
Individual user dashboard

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#258]
Meant to give the user a better overview of what is happening in his/her group.
Could be the landing page after login for every user, who already is part of at least one group.

Included info could be:
- display of the user's upcoming pickups
- display of the stores the user is part of
- display of open pick-up slots of the stores the user is part of

**Comment by tiltec** [comment]
This already exists (the group start page).

Only "display of the stores the user is part of" is not possible right now, because there is no store membership besides the group membership.

Do you think we can close this? Or are there more requirements?
