### ISSUE TITLE
Pick-up history

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#259]
Have a visible backlog of pick-ups including the foodsaver who carried out the pick-up and additional info like how much and what kind of food was saved, what went well, potential problems and miscellaneous notes. The additional info could be requested automatically when the user logs in the next time after a pick-up.

**Comment by djahnie** [comment]
This seems to touch #177, sorry didn't see it before.

**Comment by tiltec** [comment]
Yes, that already seems to be covered by the other issues.
