### ISSUE TITLE
Splash pages (login etc) have scrollbars on small screens, even if not necessary

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#264]
Is there a fixed size?

**Comment by D0nPiano** [comment]
I couldn't reproduce the error. Not showing scrollbars for me. Is it still doing it on your computer / phone?

On my computer the widest element that was not hidden somewhere was the headline "Foodsaving worldwide" - we could make it smaller `font-size: ?? vw` on smaller screens or `text-overflow: ellipsis` it.

**Comment by tiltec** [comment]
It might have been resolved with #83

**Comment by tiltec** [comment]
Is there a possibility to make the text+logo always span the screen?
