### ISSUE TITLE
Fix login backgroud image

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#270]
Background image on login page is repeating itself horizontally on big screens

**Comment by tiltec** [comment]
Can it be set to fill the screen? Sorry, only laptop people around here ;)

**Comment by ocelotluke** [comment]
That still leaves a white gap at the bottom of the screen on displays that are not the same aspect ratio as the image, why no try something like this: 

```
.splash {
    background-image: url("images/ffe07290882bf0b4838f7d91e90854ea.jpg");
    background-position: center center;
    background-size: cover;
    height: 100%;
    padding: 5% 0;
    position: fixed;
    width: 100%;
}
```

**Comment by tiltec** [comment]
@ocelotluke thanks for the hint!
This looks good on big screens, it only has the problem on mobile (less height than content size) that the content is not scrollable. Will look into this one more time...

**Comment by ocelotluke** [comment]
Hi,

That was a typo on my part, I was suppose to say "background-fixed" but your way is much cleaner.
