### ISSUE TITLE
Restructure authenticated states

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#272]
Inspired by the ui-router documentation, I suggest to restructure the authenticated states.

Currently, we use the hookProvider to redirect to "login" when the user is not authenticated. Instead, we could move those states to a parent "auth" state and use the onStart hook to intercept with the login page if necessary.

Example here: https://ui-router.github.io/ng1/docs/latest/classes/transition.transitionservice.html#onstart

```
$transitions.onStart( { to: 'auth.**' }, function(trans) {
  var $state = trans.router.stateService;
  var MyAuthService = trans.injector().get('MyAuthService');

  // If the user is not authenticated
  if (!MyAuthService.isAuthenticated()) {

    // Then return a promise for a successful login.
    // The transition will wait for this promise to settle

    return MyAuthService.authenticate().catch(function() {

      // If the authenticate() method failed for whatever reason,
      // redirect to a 'guest' state which doesn't require auth.
      return $state.target("guest");
    });
  }
});
```

Advantages:

- less code
- clearer structure
- users end up on the page that originally typed in

**Comment by D0nPiano** [comment]
Cool, sounds like a good idea!

**Comment by tiltec** [comment]
Won't look into this anymore, it didn't work out as expected. We keep the hookProvider until someone has a better solution.
