### ISSUE TITLE
Background image on splash pages (login...)

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#283]
Trying to think of a nice background image at the moment. Created a couple of textures for it, but not happy yet.
![screenshot from 2017-02-11 19-51-23](https://cloud.githubusercontent.com/assets/16825880/22856536/7f74f450-f093-11e6-8167-35fc61bae8db.png)
![repeating2](https://cloud.githubusercontent.com/assets/16825880/22856540/9280ef54-f093-11e6-850a-7ab4649c5809.jpg)
![repeating](https://cloud.githubusercontent.com/assets/16825880/22856541/92879282-f093-11e6-8536-11cca5423823.jpg)

**Comment by djahnie** [comment]
Oh nice idea to segment the little people from Luisa's drawing!
But I still like the yunity background image way better... ;)

**Comment by alangecker** [comment]
i also do like the current splash background more, but it seems quite nice as a main background  :D
![screenshot_2017-02-12_14-00-43](https://cloud.githubusercontent.com/assets/10246027/22862303/611be16e-f12c-11e6-9913-bab0fac69b24.png)

**Comment by tiltec** [comment]
Thanks @D0nPiano for creating those images! Could you upload the files here, for future reference?

I'd like to keep an _immersive_ picture on the splash pages (similar to trustroots.org). @alangecker I like your idea. Would accept a PR on this ;)

**Comment by D0nPiano** [comment]
Glad you like it! And I like the idea @alangecker! Although I think I'll make it a little more grey-ish for the usual background. Will create a PR for that.

@tiltec upload the files where? And yeah, one big one actually sounds pretty good.

**Comment by tiltec** [comment]
We close this issue because it is old. (with @nicksellen @djahnie )
