### ISSUE TITLE
GroupDetail: Description & Member Navitems not working

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#285]
On foodsaving.world, the groupDetail `stores` and `description` buttons are not working on mobile - although they do work on my laptop having my own server running.
My console says "e is undefined" but I didn't find any problems in our code yet. ...are the dependencies up to date? NavBars have not been part of Angular Material for a long time

**Comment by tiltec** [comment]
Looks like a problem with dependency injection.. maybe I shouldn't have removed ng-strict-di. Researching this.

**Comment by tiltec** [comment]
I temporarily fixed it by pushing my own build to the server. Need to investigate why circleci builds something else.

**Comment by tiltec** [comment]
It seems to work now. `Rebuild without cache` did the trick.
For the future, go here https://circleci.com/gh/yunity/foodsaving-frontend/ and retrigger the build, which will also trigger the deploy.
