### ISSUE TITLE
Duplicate translate-string for GROUP.DESCRIPTION

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#290]
GROUP.DESCRIPTION is in the translation file twice - creates some random translation errors in other languages.

**Comment by tiltec** [comment]
GROUP.DESCRIPTION was originally the string for the create and edit page.
Now there is another key needed for the tab in the mobile group view.

**Comment by tiltec** [comment]
We now have a verbose and a short description.
