### ISSUE TITLE
Group Joining: Content not scrollable

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/foodsaving-frontend#299]
When I sign up I get ask to select a group. The content is bigger than the panel, but not scrollable.

Chromium here :)

**Comment by NerdyProjects** [comment]
When I want to join another community via Join Community, I get the same content but with scrollable content. Is that a different, redundant codepath?

**Comment by D0nPiano** [comment]
Ah, I know where that problem is coming from. Will fix it later. Thanks @NerdyProjects!
