### ISSUE TITLE
Data services as factories and to return promises

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#30]
According to [this angular style guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y060), factories should be used instead of services for consistency.

Also, data services should return promises instead of resolving them.

@Sneezoo: what is your opinion on this?
Given my total inexperience as angular dev, I'd like to orient myself on the most widely spread style if it makes sense for you.

**Comment by Sneezoo** [comment]
#### Factories vs Services:
There's really no matter about using services or factories as they are basically the same thing - except the one is a *new*ed function while the other is called directly (invoked). For consistency you just use one of both, avoiding the other.
But we use ES2015 features like classes and inheritance. As factories are only available as *invoked* functions you can't use these features. As you might have seen I already used inheritance, providing some basic validation logic.
The guide you are referring to doesn't use ES2015 and therefore factories has been easier to use.

#### Promises in Data Services
You still get Promises back from the data service functions. But there's a step between as the communication services are encapsulated so only they are responsible for HTTP codes and every communication related topic. And then there are the services where the data is stored. These services do some data validation. Both of them return promises, but both do a step between to check if everything is okay before resolving and for encapsulation, too.

**Comment by Sneezoo** [comment]
Are there any objections, any suggestions or questions?
If not I would close this task in like a week so if there is any more about this topic.
Shall this explanation be added to CONTRIBUTE or README?

**Comment by tiltec** [comment]
@Sneezoo Thanks! I'm a bit overwhelmed due to the ongoing event here, but I think I understood your explanation and can use the architecture.
There's another related topic: I got introduced into ES7 _async await_ functionality by Chandi and @nicksellen , which seems to be really nice syntactic sugar over Promises. What is your opinion on them? It seems much much easier to read: http://stackabuse.com/node-js-async-await-in-es7/

**Comment by Sneezoo** [comment]
Async / await indeed is really cool.. But you will have to look out if the data reaches the controllers. You either use promises there or you try something like
```javascript
$scope.user = await users.getActiveUser();
$scope.$apply();
```
Or you use [ng-async](https://github.com/Magnetme/ng-async).
[Source](https://labs.magnet.me/nerds/2015/11/16/async-await-in-angularjs.html)

I don't know if it's valuable that much. I'd rather work on functionality (if I even have time for that) than introducing new codestyles.. <sub>(again)</sub>
But if you like to do that we should do that __now__ before starting on any other functionality so we have a final all-agreed style of code. Try it, see it how it looks and works.

**Comment by tiltec** [comment]
Ok, I might just use plain promises until AngularJS supports async/await more nicely. Thank you very much for your input!
