### ISSUE TITLE
Removing Sidebar map

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-frontend#303]
having two maps in the same time seems overloaded for me.
![screenshot_2017-02-16_10-26-00](https://cloud.githubusercontent.com/assets/10246027/23015424/0a2005a2-f433-11e6-85f6-097b6f3a4551.png)

if there is no resistance, i would do following:
- removing the one in the sidebar
- adding a map to groupDetail
- changing it that it shows always all stores, but zoomed in to the current one

**Comment by D0nPiano** [comment]
Agree that it's a little too much, but I don't get your third point. If you removed the map, why zoom into the current store? - is that another option?

I'm either for
#### 1)
> changing it that it shows always all stores, but zoomed in to the current one

and removing the map in storeDetail, or
#### 2)
just using the mobile version of storeList in desktop-mode too.

**Comment by alangecker** [comment]
the third point basically means: Having the storeDetail's map like it it (same center, same zoom) but being also able to zoom out and to see all the other stores

**Comment by tiltec** [comment]
I'd be in favour of using only the map in the sidenav, and zooming it in to the selected store.

**Comment by alangecker** [comment]
having the selected store as a state in `group` would be against the current hierarchy component structure and would require a lot of changes to implement.
@tiltec  do you think it would be worth the effort?

**Comment by tiltec** [comment]
The store list has the currently selected store already (it's highlighted). Let's see how it works!

**Comment by tiltec** [comment]
Me, @nicksellen and @djahnie agree that the maps show different things and shouldn't be reduced to one. @alangecker I will close this for now, please reopen if you want to discuss this further.
