### ISSUE TITLE
Edit/create group: selecting an address jumps to top of page

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#320]
Use Firefox, type in address and select a result. Jumps to top of page.

This seems to be a known in issue in md-select, used by md-autocomplete.
https://github.com/angular/material/issues/7273
https://github.com/angular/material/issues/3479

It works perfectly in Chrome.

There could be some workaround, manipulating the `md-click-catcher` or something...

**Comment by tiltec** [comment]
I can't reproduce this anymore, works as expected on Firefox.

**Comment by stephanradel** [comment]
I'm still experiencing page jumps to the bottom of selectbox using firefox 49.02 and IE11. To reproduce: Open https://material.angularjs.org/HEAD/demo/select, open the basic usage example in codepen, in preview window scoll down to "How do you refresh your magic?" and select a drink.

**Comment by tiltec** [comment]
It jumps for me too on codepen, but not on the main demo page. It seems like a problem of angular material to me...

Our usages seem fine, no jump on https://dev.foodsaving.world/#!/group/6/edit and https://dev.foodsaving.world/#!/group/6/store/15/edit
Do you experience jumps on those pages? (Join the 01_testgroup)

**Comment by stephanradel** [comment]
Yes, no problem on your demo page (which btw looks great). Did you implement some workarounds?
