### ISSUE TITLE
Login page: disable auto-capitalization of email and password on mobiles

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#323]
Seems to help some people to type in their credentials more correctly.

**Comment by itsmalk** [comment]
Hi!

I made some very minor changes #327 that should prevent mobiles from auto-capitalizing login info.

Unrelated, when testing the site, I ran into an issue on trying to leave a group. The site would freeze and would'nt let me click anything. Is this a known bug? I might work on it a bit for fun

**Comment by tiltec** [comment]
Hey @itsmalk, nice to see you here!
I haven't experienced this freeze, but there was a change lately (added the group leave dialog #273 ), so it's worth investigating. Can you open a new issue for this?

(By the way, are you already in our chat? slackin.yunity.org, channel foodsaving-tool)

**Comment by itsmalk** [comment]
Of Course, here it is #332
