### ISSUE TITLE
Introduction page to the foodsaving tool

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#326]
Showing off its features and its usage.
Possibly creating a how-to video, ask around in yunity.

The page could either be in this codebase or in the upcoming blog.

**Comment by tiltec** [comment]
I scribbled a text with a lot of screenshots here: https://github.com/yunity/foodsaving-docs/tree/master/foodsaving-tool-intro

What do you think? Maybe @djahnie can extend the content? ;)

**Comment by djahnie** [comment]
I love it! Actually I wasn't able to think of anything that's missing; at least not on the spot. Will give it a deeper thought next week. 👍 
Also, I guess what's most important is to keep the content up-to-date, whenever there are changes in the UI. I'll try to keep that in mind.

**Comment by tiltec** [comment]
It's in the blog now: https://blog.foodsaving.world/2017/05/11/walkthrough.html
