### ISSUE TITLE
Address auto-complete doesn't work when creating a store

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#345]
When in the small store create window the address will not get recognized, but on the store edit page it works without problems. (Instead of offering relevant preset addresses, the input field offered to insert text I had previously entered.) 
This leads to newly entered stores not coming with useful maps - even if the exact address is copy&pasted from google maps - and that a direct edit is necessary to be able to use the map.

I tested this with four addresses in Berlin and firefox.

**Comment by tiltec** [comment]
Hm.. didn't investigate, but maybe we should just move the store creation to it's own page, with a route?
It will support "back" navigation(  #284 )  then and hopefully solve this issue as well.
