### ISSUE TITLE
Discussion: data flow

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#361]
Whenever I work on the frontend, our data flow seems a bit like _Kraut und Rüben_ :) I can still work with it, but it might be hard for people who want to start contributing, so I would like to discuss this and possibly find solutions.

I wrote a long text about data flow in angular, almost a blog post. So I will put it in our blog rather than here. My preliminary conclusion: I think we should use more data services on app level and use some communication mechanism to stay updated about changes. The data services should be the point where changes happen, and components should listen to them. This seems to be similar to the uni-directional dataflow of more recent frameworks.

My questions:

- Is this solution feasible?
- Is this data flow _expected_ by angular devs? I'm not really one myself ;)
- If not: what is the angular way to solve state changes? Data binding throughout the app?

**Comment by nicksellen** [comment]
Can you describe the problem in more detail?

**Comment by tiltec** [comment]
Here's my long writing:


# Background

The frontend has to get data from backend, react to modifications made by components and also react to push notifications in future.

There are two basic methods to move data around in Angular: components and services.

## Components 

Components have bindings for data input and output.

### Input 

This is the `<` syntax, for one-way data flow from the parent component to the child. This is modern Angular style, easily understandable and future proof for Angular2+. We use that extensively.

Note that if you bind an object, they are passed via reference. That means if the child changes a property of the object, then it will also be changed at the parent. It could make sense to _deepcopy_ the elements before binding them to avoid this (_immutable_ coding style).

### Output binding

Bindings in Angular can also go the other way round: with a `&` you can pass a function. The usage is not so straightforward, so I'll give an example of this _output binding_.

We have a `delete-button` component. It has a button that the user can click on to get some values deleted.

```html
<button ng-click="$ctrl.onDelete({dataToDelete: 'my value to delete'})">Delete</button>
```

`onDelete` is a binding. The component bindings:

```json
onDelete: "&"
```

Now we embed the `delete-button` into another component's template.

```html
<delete-button on-delete="$ctrl.delete(dataToDelete)"></delete-button>
```

This will call a controller function.

```js
function delete(values) {
  // receives "my value to delete"
}
```

### Component communication

With this, we have everything we need to build a reactive web app, completely without custom services. A parent component would get all the necessary the data from the server and pass it onto its children; the children have output bindings to communicate with the parent.

The only problem will be the huge amount of bindings and function chains to communicate through the whole component hierarchy.

```
parent -> child -> childchild -> childchildchild -> childchildchildchild
```

`childchildchildchild` would need to go back through the whole chain to trigger a change in `parent`. This seems complicated.

## Services

This is why we have Services. Services are singletons, that means they are basically global objects, accessible in every context via Angular's injection mechanism. That makes them ideal as data handlers.

Services can return promises (`$http`) or values/references (`currentGroup`, `currentStores`). If you get a reference and save it, you will stay updated about its changes.

That's how `currentGroup` works. Whereever a component calls `currentGroup.set()`, it will only the change the data within the reference and angular will make sure to reflect the updates on all views. This is done via _watches_ (I think).

However, sometime you can't keep the reference. Consider:

```js
let stores = {};
Stores.listByGroup(CurrentGroup.value).then((data) => {
  stores = data;
}
```

Of course, this won't send a request to the server as soon as the group changes. So we need to take other measure to stay updated. There are some available in Angular:

- an explicit watch: `$scope.$watch('expression', fn)`
- the `$onChanges` life-cycle function in a controller
- signals with `$on('name', fn)`, sending with `$broadcast` or `$emit` (down/up the scope hierarchy)

**Comment by tiltec** [comment]
The problem is the one I tried to solve partially with this `currentStores` service: https://github.com/yunity/foodsaving-frontend/blob/8d77871d8b5682abcbd46532ce6f459340b7ee24/client/app/services/store/currentStores.service.js

Question: should we use this as recipe to synchronize state across the application? Should we do explicit watches or signals `$on` handlers to react to changes of the services' value?

**Comment by nicksellen** [comment]
If I understand correctly the scenario is:
1. there is a selected group, and it's stores are listed on the page
2. the selected group is changed
3. the list of stores should update

Is that correct?

**Comment by tiltec** [comment]
One problematic case was (handled by currentStores in master, still broken in production):
1. list of store names
2. one store's name is edited (on the store page)
3. list should reflect that changed name

Another case (handled by currentGroup in master, still broken in production):
1. edit group name
2. topbar should reflect that change

Another case (that is currently handled with a full reload from server):
1. user joins/leaves pickup
2. pickup list should reflect that change

**Comment by nicksellen** [comment]
Seems the best approach is to have directly bindable data where possible (using the `angular.copy()` method as in `currentGroup` and now `currentStores`). Everything updates automatically without any additional calls to `$watch`.

An alternative to `currentStores` would be to nest them inside the `currentGroup` (a `stores` property), but either seems fine to me.

Does `replaceItem` in `currentStores` work? I'd expect to need to either a) copy the whole list again, or b) have to use `angular.copy` to replace the item once found, e.g. `angular.copy(item, this.list[i])`. Similar for pushItem.

If it became too confusing to see all the places where `Current*` things are set, another service that manages it at a higher level could make send (and maybe move to simple `*API` services for data access, e.g. `GroupAPI`). But I don't think it would warrant it at the moment.

As I understand it `$onChanges` will only be triggered if a bound value change anyway - and in this case it would already update the UI, so it's only if you need to add additional behaviour when that change occurs.

I would avoid `$on`/`$broadcast` at all costs. Hard to trace flow/timing/dependencies. Makes testing harder. Lots of wisdom against this pattern. At least for core application operation. Scope hierarchies are confusing too.

As for data flow via component bindings - perhaps a rule of thumb is that reusable generic components should receive their data via bindings as they are just meant to be widgets to drop in anywhere, but components that are very specifically bound to a purpose (e.g. a page component, or a store selector component) could get their data via a data service.

The react/redux way is to have presentational components (take input from "bindings") and then container components that manage getting state and rendering a presentational component (see http://redux.js.org/docs/basics/UsageWithReact.html).

I don't think this clear separation needs to be followed religiously and only if the advantage is worth the extra files but it's a useful model to keep in mind. In angular this could be done by having a generic presentational component that is wrapped by a container component that gets it's state from a data service.

**Comment by nicksellen** [comment]
... and another technique in cases bigger changes are made, e.g. change group, triggering a router reload should cause any other resources to reload anyway.

**Comment by tiltec** [comment]
I agree with all of your points, except for the very first one

> Everything updates automatically without any additional calls to $watch.

That's not true, if you have a loop like 

```
let stores = {};
Stores.listByGroup(CurrentGroup.value).then((data) => {
  stores = data;
}
```

it obviously won't update. A $watch seems necessary, or is there a better way?

I can think of 
a) callbacks to register with the service
b) Observables (upcoming JS feature, used heavily in Angular 2)

EDIT: a, I see you addressed this point. But would this also be valid e.g. for the pickup list? There we have extensive logic to filter/group the pickups.

**Comment by nicksellen** [comment]
Where is the loop in that? It always need to be assigned to a property in any case, e.g.:

```
let stores = { list: [] };
Stores.listByGroup(CurrentGroup.value).then((data) => {
  stores.list = data;
}
```

However, lists do have more pitfalls than single values.

Filtering/grouping could be done using `$onChange` handler if complex, or alternatively just for filtering having a `$ctrl.isVisible(item)` function, used in the view that can check for any currently set filters should work and rerender when data changes.

**Comment by tiltec** [comment]
Yes, it's not a loop in fact ;) Sorry for the confusion, I meant to show a loop like:

```
angular.forEach(pickups, (currentPickup) => {
  currentPickup.isUserMember = currentPickup.collector_ids.indexOf(this.userId) !== -1;
  currentPickup.isFull = !(currentPickup.collector_ids.length < currentPickup.max_collectors);
})
```

The check function seems like a good approach for this.

**Comment by nicksellen** [comment]
... I was also forgetting the angular `filter` filter, which you can pass a function too https://docs.angularjs.org/api/ng/filter/filter - but the principle is the same

**Comment by tiltec** [comment]
In #389 we have an interesting issue. `$onChanges` doesn't get triggered when the content changes, it seems to watch by reference. In contrast to the usual angular databinding, which apparently does deep comparison.

I think `$onChanges` for component controllers was introduced in Angular 1.5 and it seems to point into the direction of a _one-way_ dataflow with _immutable_ objects. Am I wrong here? Ideas how to solve this problem properly?

**Comment by nicksellen** [comment]
Would be nice to get this represented in a test

**Comment by nicksellen** [comment]
First pass looks like can just remove 1 line in:
```js
$onChanges(changes) {
  if (changes.groupId && angular.isDefined(changes.groupId.currentValue)) {
    this.Store.listByGroupId(changes.groupId.currentValue).then((data) => {
      this.CurrentStores.set(data);
      this.storeList = angular.copy(this.CurrentStores.list);
    });
  }
}
```

the troublesome line is:
```js
this.storeList = angular.copy(this.CurrentStores.list);
```
The constructor already set `storeList` to `CurrentStores.list`. That line undid that by creating a new array that is no longer the one in `CurrentStores.list`.

It meant the initial list would be displayed, but subsequent changes to the list would not affect the uncoupled `storeList` array.

**Comment by nicksellen** [comment]
Should be fixed in https://github.com/yunity/foodsaving-frontend/pull/410
