### ISSUE TITLE
Use landing page title font also on splash pages

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#365]
It looks nice, could also be used on splash pages.

Alternative: since we show the logo with text on the landing page, we could remove the text "Foodsaving worldwide" from splash pages and just use the logo.

**Comment by devishi** [comment]
Do you aim to only include the logo (center aligned)?
Else, we could create a photoshop image with the logo as well as the text  "Foodsaving worldwide" to make it look consistent and explanatory?

**Comment by tiltec** [comment]
@devishi I think a image logo+text could be nice there! Maybe having two versions, one with prominent text and one with small text? 

I don't have a strong opinion yet, except that I really like vector graphics, so keeping the branding as SVG seems worthwhile to me. :)
