### ISSUE TITLE
pickupManage: add button to delete pickups

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#374]
There is already a delete dialog in `pickupList`. We could refactor it as component and use it also in pickupManage.

**Comment by TrentHand** [comment]
I'd like to work on this but I have a few questions about it.  Could we have a slack chat around this in the morning sometime this week?

**Comment by tiltec** [comment]
Hi, this is already getting resolved with #447 - although without refactoring a "delete" component. I'm not completely sure what is best for UX: moving all the delete capabilities to pickupsManage or leaving a delete button in pickupList as shortcut. I tend to favor the first option.

Happy to chat about this on Slack!
