### ISSUE TITLE
Group create/edit & store create/edit: check if name already exists

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#377]
Groups have unique names. Stores have unique names within their groups. The editCreate forms should prevent form submission if the name already exists and show an error message.

To be added to the Group and Store services:

- Filter groups by name via `/api/groups/?name=abc`
- Filter stores in group 45 by name via `/api/stores/?group=45&name=abc`
- tests

To be added to the editCreate forms and controllers:

- asynchronous validator (maybe as directive for ngInput)
- translatable error message with `ng-message`
- text string to `locale-en.json`
- tests

Maybe in two Pull Requests: first the service, then the form/controller modification.

**Comment by apoorvsgaur** [comment]
How do I assign myself to a task? I'd like to start with this.

**Comment by tiltec** [comment]
@apoorvsgaur can you estimate when you will have time to work on this task?
