### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#380]
Should we add an invitations feature to foodsaving worldwide?

Main benefit: group members could add new members by e-mail address

UX as invitation sender:

- Invitations tab for each group
- Button "invite more users"
- Dialog with input to enter one or more mail addresses.
- Click button "Invite".
- Dialog closes and invitations tab content gets updated.

UX as invitation receiver:

- If the user is already member of the group, nothing happens
- Receive a mail "You have been invited to <group name> on Foodsaving worldwide", with a link
- a) If not member on foodsaving.world: Click link, get to a page to enter name and password, click "sign up", get forwarded to group
- b) if already member of fs.world: click link, get forwarded to group

Opinions/recommendations?

**Comment by Sliverriver** [comment]
sounds nice.

**Comment by andela-tisrael** [comment]
Has a backend API been created for that?

**Comment by tiltec** [comment]
This is just an idea. We should talk in the next planning meeting if we want to include this in Release 4 (see the Milestones)

**Comment by tiltec** [comment]
https://github.com/bee-keeper/django-invitations/ could be a good inspiration for the backend side.

**Comment by tiltec** [comment]
While implementing the backend invitations model, I discovered the following special situations:

1. same e-mail address gets invited twice to the same group
2. same e-mail address gets invited to multiple groups
3. an account is already registered on the website with the e-mail address

I would handle them in these ways:

1. reject sending the second invitation
2. allow sending the second invitation
3. allow sending the invitation

(2) and (3) need a way to accept the invite without creating a new account on the website.

In case of (3) it could be nice if users could see the groups that they have been invited to on the website itself. We would need to add another endpoint where users can see the invites that they received, including the secret token.

I also thought that it makes sense to let the invitation link expire. In case (1) it means that a new invite to the same email address can't be created, so it needs special handling. When a new invitation gets created, the create command should check if there is an expired invitation with the same email address to the same group (but not necessarily by the same invited_by user), delete the expired invitation and create a new one.

Other thoughts:
What about a general invite link than can be clicked multiple times? It won't get sent out via email, but manually via other measures. This means that there would be an invite link per group and possibly per member in the group, so we can track who sent it out. If someone accepts the invite, it does not get deleted from the database (in contrast to one-time email invitation links).
With the current backend model, we could use the group password and build an invite link like `foodsaving.world/#!/signup?group=6&password=secret`. There are two downsides: (a) it's not per person who sent out the invite link, (b) the password is not supposed to expire, while a secret shared in URLs should expire for security reasons.

I considered a "apply-to-join-group" flow too: members of the group can accept people who want to join. But this seems to need a different database model than invitations, so I'll forget about it for now.
