### ISSUE TITLE
Map: Add store by clicking and improve zoom

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#391]
Right now one has to enter an address to add a store location. It would be much more intuitive and flexible if adding a store location by clicking on the map was possible.
When opening the map to enter a store location by clicking, the default zoom should be relative to the groups location.

- [ ] enable adding store locations by clicking
- [ ] localize default zoom level

**Comment by tiltec** [comment]
This should be supported in all our maps, so building a component for the store and group edit/create pages makes sense to me.

**Comment by djahnie** [comment]
Just realized gain how annoying the current way of putting store locations is...
The Ecorganic in Bilbao is displayed in the wrong corner of the street, because somehow the address is not insertable in an exact way and only ste street can be picked.
Can we make the markers draggable _very soon_, pleeeease..?

**Comment by tiltec** [comment]
Dragging around the marker is now possible in the edit screen since #445 

What do you mean by "the default zoom should be relative to the groups location."?

**Comment by djahnie** [comment]
That means that when I first want to enter the location of a store, then it should just use the location from the group detail as default. I guess the zoom level would vary because some districts are bigger than others, right?
