### ISSUE TITLE
Tidy up injection vars in tests 

### ISSUE THREAD

**Issue by nicksellen** [yunity/foodsaving-frontend#408]
This:
```js
let $scope, $ctrl, $httpBackend;
beforeEach(inject((_$rootScope_, _$compile_, $injector) => {
  $scope = _$rootScope_.$new();
  let component = _$compile_("<store-list group-id='groupId'></store-list>")($scope);
  $ctrl = component.isolateScope().$ctrl;
  $httpBackend = $injector.get("$httpBackend");
}));
```
is tidier as:
```js
let $scope, $ctrl, $httpBackend;
beforeEach(inject(($rootScope, $compile, _$httpBackend_) => {
  $scope = $rootScope.$new();
  let component = $compile("<store-list group-id='groupId'></store-list>")($scope);
  $ctrl = component.isolateScope().$ctrl;
  $httpBackend = _$httpBackend_;
}));
```
1. if you are only using the injected thing immediately, don't need to use the underscored versions
2. only need to use `$injector` for fancy special cases, in this case can get it directly (using underscored version `_$httpBackend_` so it can be assigned to non-underscored variable `$httpBackend`)

**Comment by tiltec** [comment]
With the `injector` syntax, it's one time less to type the name of the thing to inject. (3 times vs 4 times)
Also, it's easier to google in case someone wants to understand whats going on. So I would not really recommend using the underscore syntax.

**Comment by nicksellen** [comment]
I would suggest to at least choose that or the `$injector` approach then, but not both (more confusing than either approach on their own).

In my view `$injector` is introducing a deeper concept, and therefore the underscore is simpler. It's also quite common in angularjs testing world.

**Comment by tiltec** [comment]
We could also create a `this`-like object where we bind the injected services to.

```
let inj = {};
beforeEach(inject((User, Authentication) => {
Object.assign(inj, {
  User, Authentication;
}
}));
```

Hope that works. Mirrors the constructor and is even less typing.

**Comment by nicksellen** [comment]
But loses eslint unused variable checking....

**Comment by tiltec** [comment]
True, we have that problem already in controllers.

**Comment by tiltec** [comment]
Most of the time, we can avoid injections anyway. We can access everything that is already injected in the controller.

They are necessary for:
- componentController to get the controller in the first place
- $q, $rootScope to stub promises
- $httpBackend to stub $http
- if the module injects services at other places, e.g. in the stateProvider resolve functions

In test, I like to inject things where needed. If you need the `$state` service to test a transition, you could easily write:

```js
it("goes to state", (inject(($state) => {
  $state.go("somewhere");
  expect($state).to.be.something;
})));
```

and avoid `injector.get` or assigning it via the underscore syntax.
