### ISSUE TITLE
Change default backend to dev.foodsaving.world

### ISSUE THREAD

**Issue by nicksellen** [yunity/foodsaving-frontend#409]
As foodsaving.world will start to have real data, it doesn't seem a good idea to default to that.

Will knock up a PR...

**Comment by tiltec** [comment]
Should be `devdev.foodsaving.world`, right?
But I was wondering if we should move the test backend to `dev` and if necessary, have the master frontend on some other subdomain (e.g. `devui.foodsaving.world`)

**Comment by nicksellen** [comment]
... oh I guess it needs to be `devdev.foodsaving.world` as just `dev.` has same backend as main one...

Maybe should rename:
`dev.foodsaving.world` -> `beta.foodsaving.world` (not sure about beta, some other sites have urls that point to new frontends)
`devdev.foodsaving.world` -> `dev.foodsaving.world`

**Comment by tiltec** [comment]
Do we need the frontend-only deploy (currently dev) at all? It's surely nice to test frontend changes on production data and get feedback on it without running it locally.

**Comment by tiltec** [comment]
Is solved by the latest deployment changes.

https://foodsaving.world = production/production/production-db
https://dev.foodsaving.world = master/master/dev-db
