### ISSUE TITLE
Signup Captcha needed!

### ISSUE THREAD

**Issue by nicco11a** [yunity/foodsaving-frontend#413]
Anyone / thing can sign up without a Captcha, this makes it open for kids playing around too easy and it can easily be scripted for scripts that creates advertising quite easy. A captcha is needed on the signup process to avoid the foodsave-tool from being infested by spam etc.

**Comment by tiltec** [comment]
There's two things a new member can do:
1) join open groups (without password protection)
2) create new groups

If you protect your group with a password, your group should not be affected at all. I'm not against using CAPTCHAs, but would not invest time in it right now.

**Comment by nicksellen** [comment]
I agree with @tiltec. Lets wait until it becomes a problem.

**Comment by nicksellen** [comment]
I would suggest to close the issue. Can reopen in future.
