### ISSUE TITLE
Current group stays in browser after logout

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#415]
We should clear all session data on logout. Not sure if there's a general way or if we need to clear CurrentGroup & CurrentStores (and possibly more in future) individually.

Integration test would be highly welcome!

**Comment by nicksellen** [comment]
Simplest is just reload page. With browser reload. Needs no thought. But slightly ugly for user as they see a full lage refresh.

Can get fiddly doing it manually as it might not actually be all data that needs emptying - some data might be available to logged out users too. 

Could be a good use case for broadcasting a "clear" (or "logout") event broadcast that modules can handle how they wish. Alternatively having one module that pulls in all other stateful ones that can clear them when needed. But seems unnecessary to me and more fiddly.

**Comment by nicksellen** [comment]
"Session data" is a slightly confusing term here as it might be interpreted as the server session data. "Browser state" seems more accurate.

**Comment by tiltec** [comment]
I think a reload is the best option, and UX doesn't suffer much.
