### ISSUE TITLE
Remove wrapper from service generator

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#42]
I think the wrapper adds more complexity than necessary at the current state of the project. I would make sense to add it back in certain cases, but not generally. 

Some services might also be _non Com_ services, so always having a Com wrapper seems to be excessive.

Therefore, I'd remove the wrapper in generator code.

**Comment by Sneezoo** [comment]
Good! Could you please remove the wrapper of the remaining services in this PR, too?

**Comment by nicksellen** [comment]
PR is merged
