### ISSUE TITLE
Add better description and setup instructions to README.md

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#44]
- npm install etc
- backend information (dev.yunity.org live backend, local backend)
- Development process (could also go in CONTRIBUTE.md?)

**Comment by nicksellen** [comment]
Me and @Sneezoo discussed the contribution rules, and we agreed (I think!) that using `ng-click` (etc) is fine.

The rationale for avoiding them was to keep all logic in js and leave templates as simple templates so logic not spread everywhere. I suggested that this is not the angular-way and it is totally fine/usual/expected to use `ng-click`, etc. (use react et al if you want all logic in js).
