### ISSUE TITLE
Cannot reset password if email address is unverified

### ISSUE THREAD

**Issue by nicksellen** [yunity/foodsaving-frontend#440]
It results in being locked out of your account entirely as there is nothing you can do.

There is a comment in the code [1] to explain the behaviour:

> unverified addresses are not so useful to spammers

I don't really understand the logic though, it should not be possible to lock your account out.

[1] https://github.com/yunity/foodsaving-backend/blob/master/foodsaving/users/api.py#L117

**Comment by tiltec** [comment]
Yes, that's be trying to be overly cautious. Logic: don't tell people who verified his e-mail at the page.
But I guess that can go away. So: up for grabs!
