### ISSUE TITLE
Include link to our facebook group

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#454]
We have a facebook about foodsaving worldwide here: https://www.facebook.com/groups/foodsaving.worldwide/

It's getting more active, so it could make sense to link it with foodsaving.world.

**Comment by tiltec** [comment]
Include link to foodsaving.today as well.

**Comment by PabloCarmona** [comment]
I'm interested in help here. In where part of the web you want to put the link? with the fb icon I imagine.
