### ISSUE TITLE
Different icon for back button in pickupManage

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#459]
There is currently a cross icon, which could be misleading to the user. Could need a better icon, e.g. some kind of arrow.

Have a look in font-awesome and find a good one.
[Code location](https://github.com/yunity/foodsaving-frontend/blob/8d77871d8b5682abcbd46532ce6f459340b7ee24/client/app/components/group/store/pickupManage/pickupManage.html#L8)

**Comment by jeromechrist** [comment]
Hey,

How about [arrow-left](http://fontawesome.io/icon/arrow-left/) 

![image](https://cloud.githubusercontent.com/assets/2547646/25641969/2f726bc0-2f97-11e7-8de6-a6513b2f3a87.png)

**Comment by tiltec** [comment]
Best and easy choice! Please submit a PR :)
