### ISSUE TITLE
Refactor $mdMedia calls into screen size service

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#465]
We use `$mdMedia` of angular material to determine the screen size. Right now, we usually define a controller function that returns true or false, depending on the screen size.

https://github.com/yunity/foodsaving-frontend/blob/be8f67ef0498198aabc6202c0f68fb2466b154ab/client/app/components/group/store/pickupManage/_pickupManageAction/pickupManageAction.controller.js#L9
https://github.com/yunity/foodsaving-frontend/blob/4215fdd100c7e6cab97f379380df9f3a1da9488b/client/app/components/_topbar/topbar.controller.js#L4

Or it is used in the code directly.
https://github.com/yunity/foodsaving-frontend/blob/4215fdd100c7e6cab97f379380df9f3a1da9488b/client/app/components/group/groupDetail/groupDetail.html#L38

My suggestion is to create a service that provides some wrapper functions for one commonly used breakpoint (e.g. `gt-sm`), which can be accessed from the templates.

**Comment by cgomezmendez** [comment]
You mean wrapper functions like

serviceInstance.IsSmallScreen() ?
or something like that?

**Comment by tiltec** [comment]
Hi @cgomezmendez! Are you motivated to work on this?
