### ISSUE TITLE
Make pickup manage page easier to discover

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#474]
There were some reports that it's not intuitive to change the pickup settings, which is only possible on the manage pickup page.

As a solution, the prominent "create pickup" button could be replaced with a "manage pickup dates" button.

Also, I would recommend to allow deleting pickup dates only on the manage pickup page, not on the store page. It's not a commonly needed action.

**Comment by MonsieurShaik** [comment]
Hello @tiltec . I have understood the requirement. You want the Create Pickup button to be replaced with Manage pickup dates button which will redirect you to Manage pickups page.
![scrshot](https://cloud.githubusercontent.com/assets/8210079/25558060/8b35b316-2d3c-11e7-8fdf-e4b650b49bbc.PNG)

**Comment by tiltec** [comment]
Yes, very much so! Would you be happy to take this task?

**Comment by MonsieurShaik** [comment]
Sure, thanks. :)

**Comment by MonsieurShaik** [comment]
Hi @tiltec . Sorry for the delay. I have created a pull request. Here is the link.
https://github.com/yunity/foodsaving-frontend/pull/512
