### ISSUE TITLE
Fix bugs and logic errors in group URL routing 

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#484]
Opening a page https://foodsaving.world/#!/group/16/store/34 if store `34` does not exist does not show anything. The console reports a 404 error.

It should redirect to the group page.

**Comment by jbforth4** [comment]
I'll take a look at this

**Comment by tiltec** [comment]
@jbforth4 did you find out how to solve this issue?

**Comment by jbforth4** [comment]
I am still unable to get the test environment to launch the browser to
test. Without testing I am not sure the issue is.

**Comment by tiltec** [comment]
What error message arre you seeing?

**Comment by jbforth4** [comment]
It times out.  It failed at first but I modified my path variable but now it will sit for about two minutes doing nothing and then say it timed out and could not launch chrome.

**Comment by tiltec** [comment]
It seems to me that it is unable to launch Chrome. Did you get the error
message about CHROME_BIN before?

Am Montag, 22. Mai 2017 schrieb Jared :

**Comment by jbforth4** [comment]
Yeah, that was error I was getting

**Comment by tiltec** [comment]
I spent 2-3 days working on this and it seems quite painful. 

## (A) Group conditions

We need to handle the following cases about an URL like this `/group/10`

1. user can access the group (is member): go to pickups page `group.groupDetail.pickups`
2. user can't access the group
2.1. user is not member of the group: go to `groupInfo` page and show message `GROUP.NONMEMBER_REDIRECT`
2.2. user is not logged in: same as 2.1
2.3. group id does not exist: go to `landingPage` and show message "GLOBAL.NOT_FOUND"
2.4. connection is interrupted: show message about connection error (already done by `HTTPErrorHandlerConfig`)

## (B) Store conditions

Similarly for the store URLs `/group/10/store/999`

1. user can access the group (is member)
1.1 store id is valid: go to `storePickups`
1.2 store id is invalid: go to group page, probably `group.groupDetail.pickups`
2. user can't access the group: same as in (A)

## What can we do

UI-router has some techniques to get data and redirect the route: `resolve`, `redirectTo`, `onBefore`/`onStart` hooks and generally in the controller.

`resolve` runs while the state is loaded (based on `onStart`), it also runs for parent states if we transition to a child state.
`redirectTo` runs before the state is loaded (based on `onBefore`), it _does not_ run for parent states if transitioning to a child state.
`onBefore`/`onStart` hooks let us define custom matching criteria when to run code, e.g. `group.**` means all child states of `group`.
The component controllers get instantiated via `<ui-view></ui-view>` and properly run their `$onInit` lifecycle hook, also those of the parent states.

Not sure what happens when setting `abstract: true`.

## Appendix

This is a compilation of all states involved:

```js
.state("group", {
      parent: "main",
      url: "/group/{groupId:int}",
      redirectTo: ...  // group.groupDetail.pickups or groupInfo if not member
      component: "group", ...

.state("groupInfo", {
      parent: "main",
      url: "/group-info/{groupId:int}",
      component: "groupInfo", ...

.state("groupEdit", {
      parent: "group",
      url: "/edit",
      component: "groupEdit",

// ui-view container for subpages, not routable
.state("group.groupDetail", {
      abstract: true,
      component: "groupDetail"

.state("group.groupDetail.stores", {
      url: "/stores",
      redirectTo: () => {
        if ($mdMediaProvider.$get()("gt-sm")) {    // if big screen, go to main group page
          return "group";
        }
      },
      component: "stores"

// default group state, no additional url
.state("group.groupDetail.pickups", {
      component: "pickups", ...

.state("group.groupDetail.members", {
      url: "/members",
      component: "members", ...

.state("group.groupDetail.history", {
      url: "/history",
      component: "groupHistory", ..

.state("group.groupDetail.description", {
      url: "/description",
      redirectTo: () => {
        if ($mdMediaProvider.$get()("gt-sm")) {  // if big screen, go to main group page
          return "group";
        }
      },
      component: "description", ... 

// not nested, but related
.state("createGroup", {
      parent: "main",
      url: "/group/create",
      component: "createGroup", ...


// ***************************
//      store states
// ***************************
.state("group.store.storeDetail", {
      abstract: true,
      component: "storeDetail",

// ui-view container for store pages
.state("group.store", {
      url: "/store/{storeId:int}",
      redirectTo: "storePickups",
      template: "<ui-view></ui-view>",

// default store page
.state("storePickups", {
      parent: "group.store.storeDetail",
      url: "/pickups",
      component: "storePickups",

.state("storeHistory", {
      parent: "group.store.storeDetail",
      url: "/history",
      component: "storeHistory",

.state("pickupManage", {
      parent: "group.store",
      url: "/manage",
      component: "pickupManage",

// not part of the store's ui-view
.state("storeEdit", {
      parent: "group",
      url: "/store/{storeId:int}/edit",
      component: "storeEdit",

// not part of store's ui-view
.state("group.storeCreate", {
      url: "/store/create",
      component: "storeCreate",
```

**Comment by tiltec** [comment]
@nicksellen recommended to simply use the `resolve` config for the error redirects, but this needs to be wrapped inside a `timeout`.

**Comment by tiltec** [comment]
My motivation to further work on this is quite low, might postpone it.
