### ISSUE TITLE
UI/UX Issue

### ISSUE THREAD

**Issue by academy-codex** [yunity/foodsaving-frontend#530]
When you visit https://foodsaving.world/#!/landingPage link and click on the " Have a look at map arrow button " the UI becomes absurd and irresponsive. 

Have a look at the attachment. I suggest making a static front-page with only HTML,CSS, JS.
I would like to do it if assigned the task.
Thanks.

<img width="960" alt="error1" src="https://user-images.githubusercontent.com/23010145/27572457-aef461ce-5b29-11e7-9347-1544f95f319a.PNG">

**Comment by D0nPiano** [comment]
Interesting. I just tried the landing page on firefox, chrome and IE / edge, but can't reproduce your bug. The translation seems broken though - it's only displaying english for me, and I also can't change it.

And you mean building one without angular? I don't think it's really using more than HTML, CSS and JS at the moment either...

**Comment by tiltec** [comment]
(Translation is working fine for me, on foodsaving.world and dev.foodworld under firefox)

**Comment by academy-codex** [comment]
I am getting the same issue on different machines as well now. I'll look into it to understand the root cause.

**Comment by D0nPiano** [comment]
Oh, just noticed that translation is also working for me. It's just that "Blog" "Login" and "Team" are the same in english and german, and "Have a look at our map" is not yet translated 😆

**Comment by academy-codex** [comment]
Where can i find the landing page in the given github repo ?

**Comment by tiltec** [comment]
https://github.com/yunity/foodsaving-frontend/search?utf8=%E2%9C%93&q=landing+page&type=

**Comment by academy-codex** [comment]
Thanks!

**Comment by tiltec** [comment]
@academy-codex In which browser/OS did you experience the sluggish behaviour? Yours seem to be Chrome on Windows 10, right? (It works fine here in Firefox 54 on Linux)

**Comment by academy-codex** [comment]
I was infact using chrome on windows 10 at the time
