### ISSUE TITLE
Font issues with Chinese translation

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#536]
It shows like this on my laptop. We load the "Noto" font to prevent this. What to do now?

![image](https://user-images.githubusercontent.com/4410802/27760107-abdfb2f4-5e3f-11e7-962e-f8520f893ca3.png)

**Comment by nicksellen** [comment]
After trying it on my machine and @djahnie's it seems it's more an issue with @tiltec computer setup. We are all too stupid to understand how it all works, but I'm sure he can work it out with a bit of research.
