### ISSUE TITLE
Decision on service methods

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#55]
I've seen different approaches by @Sneezoo @D0nPiano and me. Would like to have one style.
1) `get(params)` where `params` can either be `{id: 1}` or a filter parameter `{group: 15}`.
2) same as above, but where `get()` also lists all entries
3) additional `list()` method, sometimes called `groups()` or the respective name
4) only `getById(id)` and `get(params)` methods with optional filtering

I would be in favour of (4), it seems clearer to me.

Also, should we always use the one-object style for parameter passing?
`save(id, update)` vs `save(obj)` with `obj = {id} + {update}`
At least for a save request, the `id` is not expected by the server as payload, would currently throw BAD_REQUEST, so would need to be filtered out before sending.

I would be in favour of `save(id, update)`.

This touches #46 #47 and surely some other contributions.

**Comment by tiltec** [comment]
also @Xbaal what do you think about this?

**Comment by D0nPiano** [comment]
My favorite is 2, because I think it's the most simple for someone who hasn't seen the code before ("if there is only one get method, I have to get the data from there".
4 also works for me because it makes it clearer that getById returns one xxx, and get(params) always returns an array of xxx.

I don't have a strong opinion on the other one. Either way works for me.

**Comment by nicksellen** [comment]
I don't think its a good idea for methods to return different types (ie
array vs object) depending on the argument passed in, so would argue for a
seperate list method. No strong view on the naming of it.

**Comment by Xbaal** [comment]
I would favour (4), because it can be confusing, if the same function can return only one object or an array of objects. `getById(id)` and `get(filterParams)` would do it. 

What do you think about wrapper functions like `getByGroupID(group)` for `get({group})`?

`save(id, update)` seems to be the way to use, because it stays obvious, what is saved/updated where.

**Comment by tiltec** [comment]
Ok.. so we go for (4) and `save(id, update)` - would rewrite the services if not done already.

@Xbaal  do you think it adds clarity to have `getByGroupID(group)`? I'm not sure if it makes the code much easier.

**Comment by Xbaal** [comment]
@tiltec I would consider adding it, if it seems to have a benefit. Right now, it won't be necessary, i think.

**Comment by nicksellen** [comment]
`get()` to me implies it will return a single result, fetched by id. Both ActiveRecord and Django ORM use this convention.

**Comment by Sneezoo** [comment]
+1 `get()` returning single objects
I'd like
*get* one object
*all/groups/list* to get all with optional filtering
*save* one object
*update* one object
*delete* one object
*save/update/deleteCollection* to save more than one object but we need to think about if this is necessary somewhere

also I think @Xbaal s idea about the wrappers is nice..
At least I'd like you to think about having two more functions wether as wrapper or not
*all/groups/listByXyzId* to get all objects related to another object of tyoe Xyz
*search* objects. Here's the question if we need it or do we implement search over all entity types?

**Comment by Sneezoo** [comment]
Ouh i forgot
*create* one object

**Comment by tiltec** [comment]
> all/groups/list to get all with optional filtering

In this case, I'm for `list`

> save/update/deleteCollection to save more than one object but we need to think about if this is necessary somewhere

This could be added when necessary. Would be different from the other methods, as it will result in multiple promises. I would resolve all promises to one (using `Promise.all`).

**Comment by Sneezoo** [comment]
As we only have verbs as methods in the services currently, I'd like to keep that. So no objections about `list`

Maybe to clarify what I said: The collection methods would/should increase performance on repeated requests. What I mean is that the frontend would send an array of objects to the backend instead of multiple requests, so there is no `Promise.all()` which we wouldn't use anyway because it doesn't work well with angular. But this is something for the future.

**Comment by Xbaal** [comment]
As we use HTTP2, this might not even be a performance problem, to do many requests.

**Comment by Sneezoo** [comment]
We do **not** use HTTP/2. Tested it with Firefox and Chrome to be sure, they both send HTTP/1.1
Maybe an issue on the backend or maybe an issue on my system. Still, requests with collections makes our frontend faster if we are in the need of operations with collections. That's the question. Do we need it / is there any real use case where collections might need to be saved/updated/deleted/...?

If not I'd just like to summarize to make things faster now:
We want to reorganize our service functions, so we have the methods:
- `get(id)` => *get* one object
- `list()` => *list* all objects
- `listByXyzId(id)` => *list* all objects filtered *by Xyz's id*
- `create(object)` => *create* an object
- `save(object)` => *save* changes for an object; to make the backend happy `id` is going to be removed before sending
- `delete(id)` => *delete* an object by id

This will result in pretty obvious code in service callers. Any objections?
If not I will create a new issue and/or pull request for this task? Ok?

**Comment by D0nPiano** [comment]
Sounds good to me. Only have to add:
- search(string) => array

**Comment by tiltec** [comment]
Looks good @Sneezoo.
I would add `update(id, changes)` additional to the `save` method, using the PATCH method of the backend. With PATCH, you only send the changed bits (partial update), while PUT requires a full representation (minus the unchangeable bits, so `id` needs to be stripped as well)

More info: http://restcookbook.com/HTTP%20Methods/patch/

So:

- `save(object)` using PUT and remove read-only fields from `object`
- `update(id, changes)` using PATCH which sends all data in `changes`

Both return a single object.

**Comment by tiltec** [comment]
HTTP/2 is used on all yunity.org domains. Check here: https://tools.keycdn.com/http2-test
My Firefox confirms the result for fstool.yunity.org

All major browsers support HTTP/2, currently with 70% adoption rate in early 2016: https://www.keycdn.com/blog/http2-statistics/

I think it's safe to assume that the average user accesses the page with HTTP/2.

**Comment by Sneezoo** [comment]
@D0nPiano thanks, somehow I forgot that method
@tiltec I was planning to use only PATCH anyways for `save(object)` but id has to be defined. `update(id, changes)` seems to be a duplicate then.
As I can see in my browsers we can't be really sure. Maybe in the future it's better supported. But that's not the point. I want to know if *collection* methods are **needed**. I think we don't need it for now.
Any more changes to the method list?

**Comment by tiltec** [comment]
@Sneezoo Ok, I'm fine with `save(object)` - leave `update` away. Both seem to do what we want.
Is there resistance against not using PUT at all? I would remove it from the backend then. I could add it back later if needed. Just keeping the Swagger small.

I agree that we don't need collection methods now. If you notice slowdown on `fstool.yunity.org`, you could investigate why HTTP/2 is not working for you. I will start monitoring the server logfiles if many people access with HTTP/1.1.

**Comment by tiltec** [comment]
I think I will push this in the next days, to get this done.
