### ISSUE TITLE
More obvious distinction between own and full pick-ups

### ISSUE THREAD

**Issue by djahnie** [yunity/foodsaving-frontend#551]
Feedback from Fürth:

Have the pick-ups taken by oneself displayed in green and the ones nobody signed up for so far in red (for example).
Maybe move the pick-ups the current user signed up for to the top, so that they are directly visible.

This can be similar in groupview and storeview.

**Comment by Sliverriver** [comment]
i like the idea to have the pickups i signed up for in a different color.

**Comment by D0nPiano** [comment]
Solved with #558
