### ISSUE TITLE
Desktop: remove storeDetail map / zoom in on sidenav

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#567]
The map on the left could easily replace the store map on desktop. Would try to implement something like this:

![screenshot from 2017-07-23 22-23-24](https://user-images.githubusercontent.com/16825880/28502573-9db07b38-6ff5-11e7-8a70-7fc57e998f02.png)

**Comment by tiltec** [comment]
Quite a good idea!
