### ISSUE TITLE
main panel is vertically centered

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#570]
![image](https://user-images.githubusercontent.com/4410802/28518888-dc9720ee-7069-11e7-9431-cf1283919d3e.png)

It seems to be caused by this line:
https://github.com/yunity/foodsaving-frontend/blob/8763988e244212a880165d29f5e980fdcf142223/client/app/components/_mainLayout/mainLayout.styl#L5

@D0nPiano can you give me insight why you added "margin auto"? Can it be removed or replaced?

**Comment by D0nPiano** [comment]
Just noticed that yesterday too - I already solved it locally on the new groupMap. Going to be fixed soon 🙂

**Comment by D0nPiano** [comment]
Closed with #569
