### ISSUE TITLE
chai-as-promised change needed?

### ISSUE THREAD

**Issue by Xbaal** [yunity/foodsaving-frontend#58]
After merging #57 I just found this:
https://github.com/vlkosinov/karma-chai-as-promised#usage

It states, that the order of the framework declaration in the karma config makes a difference.
I tested the functionality of chai-as-promised and it worked, so it might not be of siginificance.

So this issue might be void, it's more like a reminder, that there could be caused some problems.
And as well a proposition to not use [karma-chai-plugins](https://www.npmjs.com/package/karma-chai-plugins), but [karma-chai-as-promised](https://github.com/vlkosinov/karma-chai-as-promised), which is just a smaller set of plugins (only the one i included).

**Comment by tiltec** [comment]
Didn't see any problems so far. We don't need the other plugins right now, so I would suggest to switch to `karma-chai-as-promised`.

**Comment by Xbaal** [comment]
Since other plugins might be very useful, like `sinon-chai`, @tiltec and me decided to stick to `karma-chai-plugins`
