### ISSUE TITLE
Create a 404 NOT FOUND page

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#589]
@D0nPiano are you motivated to create a _not found_ page for those cases (from #484 )?

- group id does not exist
- store id does not exist (in the group)

We could redirect to them in the `resolve` configs from #588 .

**Comment by tiltec** [comment]
Probably also

- user id not found

**Comment by D0nPiano** [comment]
Sure, will probably have some time to draw / click something together tomorrow :)
