### ISSUE TITLE
Fix bug: changing recurring pickups also changes pickup dates already joined by users

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/foodsaving-frontend#596]
Reporting following bug: Changing a series of recurring pickups also changes the date of pickups that people had already joined.

Detailed description: I changed a series of recurring pickups, from Tue and Thu to Wed and Fri. People had already joined one pickup on the next Tuesday, and when I changed the series, their pickup date (already assigned) changed automatically to Wednesday. The system should preserve (or at least ask if the user really wants to change) the pickup dates that people have already joined.

Btw, rookie question, how do I add the label:bug?

**Comment by tiltec** [comment]
Ah interesting! I'm not completely sure, but I think it should not happen. Need to investigate this further.

A quick workaround: change the time of the pickup date, then it should stay as it is.

**Comment by tiltec** [comment]
I can add labels with this form on the right:

![image](https://user-images.githubusercontent.com/4410802/29253732-ddc62f10-8085-11e7-8949-05fe2a6a0d62.png)

If you don't have it, it's maybe because you are not a member of the yunity organization. I can add you to it!

**Comment by brnsolikyl** [comment]
Yep, I "fixed" it just like you said! :)
This bug can be a bit risky in case the person who changes does not pay attention, or if there are a lot of pickups which people already joined on a particular series of recurring dates. Also, in the future, when/if we have notifications about upcoming pickups that users joined, it might cause some trouble!

Oh, I didn't have access, that explains. Thx!

**Comment by tiltec** [comment]
Should the same principle (not changing the pickup date when people have joined it) be applied when changing the "additional information" field of the series and the "maximum number of collectors"?

For example, if you have "additional information" in the series, than per default all pickups will inherit it.
Now if someone joins the pickup and you change the "additional information" of the series.
Should the information of the pickup also be changed?

What about the maximum number of collectors?

It's a bit tricky, this stuff!

**Comment by brnsolikyl** [comment]
Tricky indeed!! For additional info and number of collectors, I'd say no. But just because, from my point of view, it's more intuitive that if one information on the joined pickups is not changed (date), the rest should not change either. So the pickups that people joined can only be modified individually.
But idk, maybe there's a user case where this would be a stupid thing! hehe

**Comment by tiltec** [comment]
Here's a fix for the behaviour that you mentioned in the first post (changed date).
https://github.com/yunity/foodsaving-backend/pull/346

I'm not sure about the other fields. But as you said, maybe it makes sense to treat them the same for consistency.

**Comment by tiltec** [comment]
This behavior will change again to work around problems when changing recurring pickups. In future, when a series changes, pickups will get cancelled when they don't match the series.
More details & discussion here: https://community.foodsaving.world/t/better-change-handling-for-recurring-pickups/174/5
