### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by ajayns** [yunity/foodsaving-frontend#603]
I've noticed a few minor issues in the user interface in the homepage itself. 
![image](https://user-images.githubusercontent.com/20743219/29861760-fd4e5eca-8d87-11e7-91ab-5651a61c0342.png)
So here, the cursor is not set to pointer so it doesn't look or feel like a link.
![image](https://user-images.githubusercontent.com/20743219/29861799-25c84014-8d88-11e7-9bfe-451b0d65cf73.png)
Few improvements to be made here would be to remove the underline so make it go better with the overall design. Also the map needs to be given a border or rounded edges so it looks better blended with the webpage.

**Comment by tiltec** [comment]
Hi @ajayns, thanks for reporting the issue! We are migrating the landing page to a static website in #601. Would you be interested to help us?

**Comment by ajayns** [comment]
Hey @tiltec, that's great. I'd love to help, let me go through the discussion there.

**Comment by tiltec** [comment]
Cool :) You can also join our slack via slackin.yunity.org, have a look inside the #foodsaving-tool channel 🚀
