### ISSUE TITLE
Rename of "groups" component

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#70]
I don't really like the name "groups" for the groupContainer anymore. Thinking of just renaming it to "groupContainer" and now creating a "storeContainer" for the store page - and objections? Or other naming ideas?

**Comment by tiltec** [comment]
What about `groupDetail` for the group itself, and if there is a separate list of groups, call it `groupList`.

**Comment by D0nPiano** [comment]
Going to rename it to _groupDetail.
