### ISSUE TITLE
Different purposes of GroupDetail and StoreDetail

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#86]
It appears to me that @D0nPiano designed PickupList to be usable in GroupDetail, as well as a future StoreDetail page.
The PickupList has the additional parameter `showDetail`, which defaults to `date`, but is [currently only used](https://github.com/yunity/foodsaving-frontend/blob/master/client/app/components/groupDetail/groupDetail.html#L9) with `store`.

The bigger question to me is how different the GroupDetail and StoreDetail pages will be?

My view on this: 
## GroupDetail

Central page for a group, with the upcoming empty pickup slots and pickups slots where the user entered himself (=tasks to do, tasks that I promised to do). A list of all users, possibility to send messages to them (to discuss), a map of all stores in the group (to discuss)

In future, it could show recent updates to store descriptions and to posts in team chats (not implemented yet)
## StoreDetail

Show and edit the name & description, show all pickups (also completely filled ones), add new pickups, show pickup history (to discuss)

In future, it could show a team chat and let you post in it (not implemented yet).
# Summary

The different purpose of those could lead to different designs, e.g. the list of pickups in the GroupDetail may be simplified, without the filtering and sorting options, whereas the StoreDetail page is much more complex, as should mostly used be users (think store managers) who need these functions anyway.

**Comment by D0nPiano** [comment]
I pretty much think the same - I'd leave it as the same component for now and just change the options with bindings.

I'd still like to remove th groupByDate sticky-headers when showDetail is "date". Other than that I find "showDetail" and "showCreateButton" to be sufficient for a difference between store & group page at the moment.

**Comment by D0nPiano** [comment]
Is this still up-to-date, or can we close it? The changes in pickuplist solved the points mentioned above I think.

**Comment by tiltec** [comment]
@D0nPiano I'm in favor of splitting, but other things are more important. The split gives us more flexibility, e.g. when redesigning the groupDetail page.

**Comment by tiltec** [comment]
Hm... how do you feel about moving it to two different components? I added another ng-if to the template in #219 and I found it a bit hard to understand what content is actually shown.

**Comment by tiltec** [comment]
Ok, I'm going to close this for now. Seems to be flexible enough ;)
