### ISSUE TITLE
Add translation support to the frontend

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-frontend#90]
As we are building a platform for worldwide usage and not everybody speaks English, translation support is paramount.

I looked a bit around and found an angular package:
https://github.com/angular-translate/angular-translate
Should we use it? There doesn't seem to be out-of-box support for this in angular. It seems quite simple to use, just feed it with an object of translation strings:
https://angular-translate.github.io/

There's also another package, but much less active:
https://github.com/rubenv/angular-gettext

**Comment by nicksellen** [comment]
I used it before (for https://www.letmake.com). I think it is good!

**Comment by tiltec** [comment]
Closed with #112
