### ISSUE TITLE
Rewrite Service Methods

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#92]
Since the decision on service methods seems to be done, We shall rewrite them like:

- `get(id)` => *get* one object
- `list()` => *list* all objects
- `listByXyzId(id)` => *list* all objects filtered *by Xyz's id*
- `create(object)` => *create* an object
- `save(object)` => *save* changes for an object; to make the backend happy `id` is going to be removed before sending using PATCH
- `delete(id)` => *delete* an object by id
- `search(string)` => *search* for an object by string

Are you, @tiltec working on it? Otherwise I'd probably asign myself :)

**Comment by tiltec** [comment]
@D0nPiano - I could be working on it tomorrow. If you want to start tonight or so, please go ahead :) Otherwise I will assign myself as soon as I start touching code.

**Comment by D0nPiano** [comment]
Cool! I think I'll just work on the components some more then.
