### ISSUE TITLE
Dialog Service for Create Panels

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-frontend#93]
Create a Dialog service, that makes opening Angular panels more pretty.

Panels:
https://material.angularjs.org/1.1.1/demo/panel

**Comment by nicksellen** [comment]
I think there is some confusion about Dialogs vs Panels. The docs say:

> $mdPanel is a robust, low-level service for creating floating panels on the screen. It can be used to implement tooltips, dialogs, pop-ups, etc.

> $mdDialog opens a dialog over the app to inform users about critical information or require them to make decisions. There are two approaches for setup: a simple promise API and regular object syntax.

So, `$mdPanel` is quite general and low level, `$mdDialog` sounds like the service you are proposing to create, it can be used like this (not following our style convention though):

```js
  $scope.showPrompt = function(ev) {
    // Appending dialog to document.body to cover sidenav in docs app
    var confirm = $mdDialog.prompt()
      .title('What would you name your dog?')
      .textContent('Bowser is a common name.')
      .placeholder('Dog name')
      .ariaLabel('Dog name')
      .initialValue('Buddy')
      .targetEvent(ev)
      .ok('Okay!')
      .cancel('I\'m a cat person');

    $mdDialog.show(confirm).then(function(result) {
      $scope.status = 'You decided to name your dog ' + result + '.';
    }, function() {
      $scope.status = 'You didn\'t name your dog.';
    });
  };
```
(from https://material.angularjs.org/1.1.1/demo/dialog)

**Comment by D0nPiano** [comment]
Well, my thought was that the $mdPanel service still has too many options though, and that a dialog service could be used to just have a simple "open("createPickups")" function, without you having to worry where it's placed, if another one is opened etc..
So basically a wrapper for $mdPanel.
But I'm going to research if $mdPanel could also be used writing as little code as possible for opening one.
